import pandas as pd
import requests

result_columns = ["city"]
locations = [
    "Copenhagen, Denmark",
    "Brussels, Belgium",
    "Lodz, Poland",
    "Islamabad, Pakistan",
]
keys = ["temp", "windspeed"]
scope = 2
key = "JHAYLP4FXDAJM4N3NJ9VYSMPM"  # "UAGFQCZD5BGZ74Y3LRJ7GK6WL"

# for location in locations:

json_request = {
    "queryCost": 48,
    "latitude": 55.6757,
    "longitude": 12.5676,
    "resolvedAddress": "København, Hovedstaden, Danmark",
    "address": "Copenhagen, Denmark",
    "timezone": "Europe/Copenhagen",
    "tzoffset": 2.0,
    "days": [
        {
            "datetime": "2023-04-10",
            "datetimeEpoch": 1681077600,
            "tempmax": 9.7,
            "tempmin": 3.8,
            "temp": 6.7,
            "feelslikemax": 6.6,
            "feelslikemin": 0.2,
            "feelslike": 3.3,
            "dew": 0.9,
            "humidity": 66.9,
            "precip": 0.0,
            "precipprob": 0.0,
            "precipcover": 0.0,
            "preciptype": None,
            "snow": 0.0,
            "snowdepth": 0.0,
            "windgust": 44.3,
            "windspeed": 33.0,
            "winddir": 125.8,
            "pressure": 1022.9,
            "cloudcover": 70.8,
            "visibility": 10.0,
            "solarradiation": 354.8,
            "solarenergy": 18.0,
            "uvindex": 7.0,
            "sunrise": "06:18:31",
            "sunriseEpoch": 1681100311,
            "sunset": "20:05:04",
            "sunsetEpoch": 1681149904,
            "moonphase": 0.65,
            "conditions": "Partially cloudy",
            "description": "Partly cloudy throughout the day.",
            "icon": "partly-cloudy-day",
            "stations": ["E7634", "ESMS", "EKCH", "EKRK"],
            "source": "obs",
            "hours": [
                {
                    "datetime": "00:00:00",
                    "datetimeEpoch": 1681077600,
                    "temp": 4.8,
                    "feelslike": 2.6,
                    "humidity": 70.78,
                    "dew": 0.0,
                    "precip": 0.0,
                    "precipprob": 0.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": None,
                    "windgust": 11.9,
                    "windspeed": 9.6,
                    "winddir": 101.0,
                    "pressure": 1027.9,
                    "visibility": 10.0,
                    "cloudcover": 29.5,
                    "solarradiation": None,
                    "solarenergy": None,
                    "uvindex": None,
                    "conditions": "Partially cloudy",
                    "icon": "partly-cloudy-night",
                    "stations": ["ESMS", "EKCH", "EKRK"],
                    "source": "obs",
                },
                {
                    "datetime": "01:00:00",
                    "datetimeEpoch": 1681081200,
                    "temp": 4.9,
                    "feelslike": 2.6,
                    "humidity": 61.67,
                    "dew": -1.9,
                    "precip": 0.0,
                    "precipprob": 0.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": None,
                    "windgust": 13.7,
                    "windspeed": 9.7,
                    "winddir": 101.0,
                    "pressure": 1027.9,
                    "visibility": 10.0,
                    "cloudcover": 88.0,
                    "solarradiation": None,
                    "solarenergy": None,
                    "uvindex": None,
                    "conditions": "Partially cloudy",
                    "icon": "partly-cloudy-night",
                    "stations": ["ESMS", "EKCH", "EKRK"],
                    "source": "obs",
                },
                {
                    "datetime": "02:00:00",
                    "datetimeEpoch": 1681084800,
                    "temp": 3.9,
                    "feelslike": 1.1,
                    "humidity": 66.16,
                    "dew": -1.8,
                    "precip": 0.0,
                    "precipprob": 0.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": None,
                    "windgust": 16.6,
                    "windspeed": 11.2,
                    "winddir": 111.0,
                    "pressure": 1027.9,
                    "visibility": 10.0,
                    "cloudcover": 88.0,
                    "solarradiation": None,
                    "solarenergy": None,
                    "uvindex": None,
                    "conditions": "Partially cloudy",
                    "icon": "partly-cloudy-night",
                    "stations": ["ESMS", "EKCH", "EKRK"],
                    "source": "obs",
                },
                {
                    "datetime": "03:00:00",
                    "datetimeEpoch": 1681088400,
                    "temp": 3.8,
                    "feelslike": 0.7,
                    "humidity": 76.04,
                    "dew": 0.0,
                    "precip": 0.0,
                    "precipprob": 0.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": None,
                    "windgust": 16.6,
                    "windspeed": 12.9,
                    "winddir": 120.0,
                    "pressure": 1027.9,
                    "visibility": 10.0,
                    "cloudcover": 88.0,
                    "solarradiation": None,
                    "solarenergy": None,
                    "uvindex": None,
                    "conditions": "Partially cloudy",
                    "icon": "partly-cloudy-night",
                    "stations": ["ESMS", "EKCH", "EKRK"],
                    "source": "obs",
                },
                {
                    "datetime": "04:00:00",
                    "datetimeEpoch": 1681092000,
                    "temp": 3.9,
                    "feelslike": 1.1,
                    "humidity": 81.2,
                    "dew": 1.0,
                    "precip": 0.0,
                    "precipprob": 0.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": None,
                    "windgust": 15.8,
                    "windspeed": 11.4,
                    "winddir": 110.0,
                    "pressure": 1027.9,
                    "visibility": 10.0,
                    "cloudcover": 50.0,
                    "solarradiation": None,
                    "solarenergy": None,
                    "uvindex": None,
                    "conditions": "Partially cloudy",
                    "icon": "partly-cloudy-night",
                    "stations": ["ESMS", "EKCH", "EKRK"],
                    "source": "obs",
                },
                {
                    "datetime": "05:00:00",
                    "datetimeEpoch": 1681095600,
                    "temp": 3.8,
                    "feelslike": 1.0,
                    "humidity": 81.19,
                    "dew": 0.9,
                    "precip": 0.0,
                    "precipprob": 0.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": None,
                    "windgust": 15.8,
                    "windspeed": 11.3,
                    "winddir": 110.0,
                    "pressure": 1026.9,
                    "visibility": 10.0,
                    "cloudcover": 48.2,
                    "solarradiation": None,
                    "solarenergy": None,
                    "uvindex": None,
                    "conditions": "Partially cloudy",
                    "icon": "partly-cloudy-night",
                    "stations": ["ESMS", "EKCH", "EKRK"],
                    "source": "obs",
                },
                {
                    "datetime": "06:00:00",
                    "datetimeEpoch": 1681099200,
                    "temp": 3.8,
                    "feelslike": 0.7,
                    "humidity": 75.91,
                    "dew": 0.0,
                    "precip": 0.0,
                    "precipprob": 0.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": None,
                    "windgust": 17.6,
                    "windspeed": 13.1,
                    "winddir": 110.0,
                    "pressure": 1026.9,
                    "visibility": 10.0,
                    "cloudcover": 25.0,
                    "solarradiation": None,
                    "solarenergy": None,
                    "uvindex": None,
                    "conditions": "Partially cloudy",
                    "icon": "partly-cloudy-night",
                    "stations": ["ESMS", "EKCH", "EKRK"],
                    "source": "obs",
                },
                {
                    "datetime": "07:00:00",
                    "datetimeEpoch": 1681102800,
                    "temp": 3.9,
                    "feelslike": 0.2,
                    "humidity": 76.05,
                    "dew": 0.1,
                    "precip": 0.0,
                    "precipprob": 0.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": None,
                    "windgust": 17.6,
                    "windspeed": 16.4,
                    "winddir": 120.0,
                    "pressure": 1025.9,
                    "visibility": 10.0,
                    "cloudcover": 50.0,
                    "solarradiation": 5.0,
                    "solarenergy": 0.0,
                    "uvindex": 0.0,
                    "conditions": "Partially cloudy",
                    "icon": "partly-cloudy-day",
                    "stations": ["E7634", "ESMS", "EKCH", "EKRK"],
                    "source": "obs",
                },
                {
                    "datetime": "08:00:00",
                    "datetimeEpoch": 1681106400,
                    "temp": 5.0,
                    "feelslike": 1.7,
                    "humidity": 70.8,
                    "dew": 0.1,
                    "precip": 0.0,
                    "precipprob": 0.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": None,
                    "windgust": 20.9,
                    "windspeed": 15.2,
                    "winddir": 120.0,
                    "pressure": 1026.0,
                    "visibility": 10.0,
                    "cloudcover": 89.1,
                    "solarradiation": 130.0,
                    "solarenergy": 0.5,
                    "uvindex": 1.0,
                    "conditions": "Partially cloudy",
                    "icon": "partly-cloudy-day",
                    "stations": ["E7634", "ESMS", "EKCH", "EKRK"],
                    "source": "obs",
                },
                {
                    "datetime": "09:00:00",
                    "datetimeEpoch": 1681110000,
                    "temp": 5.9,
                    "feelslike": 2.5,
                    "humidity": 71.23,
                    "dew": 1.1,
                    "precip": 0.0,
                    "precipprob": 0.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": None,
                    "windgust": 26.6,
                    "windspeed": 17.2,
                    "winddir": 130.0,
                    "pressure": 1025.9,
                    "visibility": 10.0,
                    "cloudcover": 83.1,
                    "solarradiation": 367.0,
                    "solarenergy": 1.3,
                    "uvindex": 4.0,
                    "conditions": "Partially cloudy",
                    "icon": "partly-cloudy-day",
                    "stations": ["E7634", "ESMS", "EKCH", "EKRK"],
                    "source": "obs",
                },
                {
                    "datetime": "10:00:00",
                    "datetimeEpoch": 1681113600,
                    "temp": 6.9,
                    "feelslike": 3.6,
                    "humidity": 66.06,
                    "dew": 1.0,
                    "precip": 0.0,
                    "precipprob": 0.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": None,
                    "windgust": 32.0,
                    "windspeed": 19.2,
                    "winddir": 130.0,
                    "pressure": 1025.9,
                    "visibility": 10.0,
                    "cloudcover": 25.0,
                    "solarradiation": 462.0,
                    "solarenergy": 1.7,
                    "uvindex": 5.0,
                    "conditions": "Partially cloudy",
                    "icon": "partly-cloudy-day",
                    "stations": ["E7634", "ESMS", "EKCH", "EKRK"],
                    "source": "obs",
                },
                {
                    "datetime": "11:00:00",
                    "datetimeEpoch": 1681117200,
                    "temp": 8.8,
                    "feelslike": 5.5,
                    "humidity": 58.11,
                    "dew": 1.0,
                    "precip": 0.0,
                    "precipprob": 0.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": None,
                    "windgust": 36.7,
                    "windspeed": 24.4,
                    "winddir": 138.0,
                    "pressure": 1025.0,
                    "visibility": 10.0,
                    "cloudcover": 98.0,
                    "solarradiation": 568.0,
                    "solarenergy": 2.0,
                    "uvindex": 6.0,
                    "conditions": "Overcast",
                    "icon": "cloudy",
                    "stations": ["E7634", "ESMS", "EKCH", "EKRK"],
                    "source": "obs",
                },
                {
                    "datetime": "12:00:00",
                    "datetimeEpoch": 1681120800,
                    "temp": 8.8,
                    "feelslike": 5.5,
                    "humidity": 54.16,
                    "dew": 0.0,
                    "precip": 0.0,
                    "precipprob": 0.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": None,
                    "windgust": 39.6,
                    "windspeed": 24.5,
                    "winddir": 139.0,
                    "pressure": 1024.9,
                    "visibility": 10.0,
                    "cloudcover": 98.2,
                    "solarradiation": 649.0,
                    "solarenergy": 2.3,
                    "uvindex": 6.0,
                    "conditions": "Overcast",
                    "icon": "cloudy",
                    "stations": ["E7634", "ESMS", "EKCH", "EKRK"],
                    "source": "obs",
                },
                {
                    "datetime": "13:00:00",
                    "datetimeEpoch": 1681124400,
                    "temp": 9.0,
                    "feelslike": 5.1,
                    "humidity": 56.98,
                    "dew": 0.9,
                    "precip": 0.0,
                    "precipprob": 0.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": None,
                    "windgust": 42.1,
                    "windspeed": 31.5,
                    "winddir": 140.0,
                    "pressure": 1024.0,
                    "visibility": 10.0,
                    "cloudcover": 89.9,
                    "solarradiation": 682.0,
                    "solarenergy": 2.5,
                    "uvindex": 7.0,
                    "conditions": "Partially cloudy",
                    "icon": "partly-cloudy-day",
                    "stations": ["E7634", "ESMS", "EKCH"],
                    "source": "obs",
                },
                {
                    "datetime": "14:00:00",
                    "datetimeEpoch": 1681128000,
                    "temp": 8.8,
                    "feelslike": 5.2,
                    "humidity": 58.22,
                    "dew": 1.0,
                    "precip": 0.0,
                    "precipprob": 0.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": None,
                    "windgust": 44.3,
                    "windspeed": 28.1,
                    "winddir": 139.0,
                    "pressure": 1022.9,
                    "visibility": 10.0,
                    "cloudcover": 100.0,
                    "solarradiation": 668.0,
                    "solarenergy": 2.4,
                    "uvindex": 7.0,
                    "conditions": "Overcast",
                    "icon": "cloudy",
                    "stations": ["E7634", "ESMS", "EKCH", "EKRK"],
                    "source": "obs",
                },
                {
                    "datetime": "15:00:00",
                    "datetimeEpoch": 1681131600,
                    "temp": 9.7,
                    "feelslike": 6.6,
                    "humidity": 54.96,
                    "dew": 1.1,
                    "precip": 0.0,
                    "precipprob": 0.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": None,
                    "windgust": 44.3,
                    "windspeed": 24.8,
                    "winddir": 130.0,
                    "pressure": 1022.0,
                    "visibility": 10.0,
                    "cloudcover": 100.0,
                    "solarradiation": 571.0,
                    "solarenergy": 2.1,
                    "uvindex": 6.0,
                    "conditions": "Overcast",
                    "icon": "cloudy",
                    "stations": ["E7634", "ESMS", "EKCH", "EKRK"],
                    "source": "obs",
                },
                {
                    "datetime": "16:00:00",
                    "datetimeEpoch": 1681135200,
                    "temp": 9.7,
                    "feelslike": 6.4,
                    "humidity": 58.36,
                    "dew": 2.0,
                    "precip": 0.0,
                    "precipprob": 0.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": None,
                    "windgust": 44.3,
                    "windspeed": 28.0,
                    "winddir": 130.0,
                    "pressure": 1020.9,
                    "visibility": 10.0,
                    "cloudcover": 100.0,
                    "solarradiation": 428.0,
                    "solarenergy": 1.5,
                    "uvindex": 4.0,
                    "conditions": "Overcast",
                    "icon": "cloudy",
                    "stations": ["E7634", "ESMS", "EKCH", "EKRK"],
                    "source": "obs",
                },
                {
                    "datetime": "17:00:00",
                    "datetimeEpoch": 1681138800,
                    "temp": 8.8,
                    "feelslike": 5.4,
                    "humidity": 62.03,
                    "dew": 2.0,
                    "precip": 0.0,
                    "precipprob": 0.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": None,
                    "windgust": 42.8,
                    "windspeed": 26.1,
                    "winddir": 130.0,
                    "pressure": 1020.0,
                    "visibility": 10.0,
                    "cloudcover": 100.0,
                    "solarradiation": 246.0,
                    "solarenergy": 0.9,
                    "uvindex": 2.0,
                    "conditions": "Overcast",
                    "icon": "cloudy",
                    "stations": ["E7634", "ESMS", "EKCH", "EKRK"],
                    "source": "obs",
                },
                {
                    "datetime": "18:00:00",
                    "datetimeEpoch": 1681142400,
                    "temp": 8.8,
                    "feelslike": 5.3,
                    "humidity": 62.63,
                    "dew": 2.0,
                    "precip": 0.0,
                    "precipprob": 0.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": None,
                    "windgust": 42.1,
                    "windspeed": 26.2,
                    "winddir": 129.0,
                    "pressure": 1018.9,
                    "visibility": 10.0,
                    "cloudcover": 50.0,
                    "solarradiation": 126.0,
                    "solarenergy": 0.5,
                    "uvindex": 1.0,
                    "conditions": "Partially cloudy",
                    "icon": "partly-cloudy-day",
                    "stations": ["E7634", "ESMS", "EKCH", "EKRK"],
                    "source": "obs",
                },
                {
                    "datetime": "19:00:00",
                    "datetimeEpoch": 1681146000,
                    "temp": 7.8,
                    "feelslike": 3.9,
                    "humidity": 66.7,
                    "dew": 2.0,
                    "precip": 0.0,
                    "precipprob": 0.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": None,
                    "windgust": 42.1,
                    "windspeed": 27.9,
                    "winddir": 120.0,
                    "pressure": 1017.0,
                    "visibility": 10.0,
                    "cloudcover": 50.0,
                    "solarradiation": 44.0,
                    "solarenergy": 0.2,
                    "uvindex": 0.0,
                    "conditions": "Partially cloudy",
                    "icon": "partly-cloudy-day",
                    "stations": ["E7634", "ESMS", "EKCH", "EKRK"],
                    "source": "obs",
                },
                {
                    "datetime": "20:00:00",
                    "datetimeEpoch": 1681149600,
                    "temp": 7.8,
                    "feelslike": 3.8,
                    "humidity": 66.9,
                    "dew": 2.0,
                    "precip": 0.0,
                    "precipprob": 0.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": None,
                    "windgust": 41.0,
                    "windspeed": 29.2,
                    "winddir": 120.0,
                    "pressure": 1016.0,
                    "visibility": 10.0,
                    "cloudcover": 88.0,
                    "solarradiation": 21.0,
                    "solarenergy": 0.1,
                    "uvindex": 0.0,
                    "conditions": "Partially cloudy",
                    "icon": "partly-cloudy-day",
                    "stations": ["E7634", "ESMS", "EKCH", "EKRK"],
                    "source": "obs",
                },
                {
                    "datetime": "21:00:00",
                    "datetimeEpoch": 1681153200,
                    "temp": 7.8,
                    "feelslike": 3.5,
                    "humidity": 66.9,
                    "dew": 2.0,
                    "precip": 0.0,
                    "precipprob": 0.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": None,
                    "windgust": 43.6,
                    "windspeed": 33.0,
                    "winddir": 120.0,
                    "pressure": 1015.0,
                    "visibility": 10.0,
                    "cloudcover": 83.5,
                    "solarradiation": None,
                    "solarenergy": None,
                    "uvindex": None,
                    "conditions": "Partially cloudy",
                    "icon": "partly-cloudy-night",
                    "stations": ["ESMS", "EKCH", "EKRK"],
                    "source": "obs",
                },
                {
                    "datetime": "22:00:00",
                    "datetimeEpoch": 1681156800,
                    "temp": 7.8,
                    "feelslike": 3.6,
                    "humidity": 66.9,
                    "dew": 2.0,
                    "precip": 0.0,
                    "precipprob": 0.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": None,
                    "windgust": 44.3,
                    "windspeed": 31.6,
                    "winddir": 130.0,
                    "pressure": 1014.0,
                    "visibility": 10.0,
                    "cloudcover": 25.0,
                    "solarradiation": None,
                    "solarenergy": None,
                    "uvindex": None,
                    "conditions": "Partially cloudy",
                    "icon": "partly-cloudy-night",
                    "stations": ["ESMS", "EKCH", "EKRK"],
                    "source": "obs",
                },
                {
                    "datetime": "23:00:00",
                    "datetimeEpoch": 1681160400,
                    "temp": 6.9,
                    "feelslike": 2.3,
                    "humidity": 76.19,
                    "dew": 3.0,
                    "precip": 0.0,
                    "precipprob": 0.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": None,
                    "windgust": 44.3,
                    "windspeed": 32.9,
                    "winddir": 121.0,
                    "pressure": 1013.0,
                    "visibility": 10.0,
                    "cloudcover": 52.7,
                    "solarradiation": None,
                    "solarenergy": None,
                    "uvindex": None,
                    "conditions": "Partially cloudy",
                    "icon": "partly-cloudy-night",
                    "stations": ["ESMS", "EKCH", "EKRK"],
                    "source": "obs",
                },
            ],
        },
        {
            "datetime": "2023-04-11",
            "datetimeEpoch": 1681164000,
            "tempmax": 9.9,
            "tempmin": 5.0,
            "temp": 7.8,
            "feelslikemax": 9.9,
            "feelslikemin": 2.5,
            "feelslike": 5.2,
            "dew": 5.5,
            "humidity": 85.5,
            "precip": 6.4,
            "precipprob": 100.0,
            "precipcover": 45.83,
            "preciptype": ["rain"],
            "snow": 0.0,
            "snowdepth": 0.0,
            "windgust": 49.3,
            "windspeed": 33.2,
            "winddir": 165.9,
            "pressure": 1006.4,
            "cloudcover": 80.1,
            "visibility": 9.2,
            "solarradiation": 163.1,
            "solarenergy": 8.2,
            "uvindex": 5.0,
            "sunrise": "06:15:58",
            "sunriseEpoch": 1681186558,
            "sunset": "20:07:05",
            "sunsetEpoch": 1681236425,
            "moonphase": 0.69,
            "conditions": "Rain, Partially cloudy",
            "description": "Partly cloudy throughout the day with rain.",
            "icon": "rain",
            "stations": ["E7634", "ESMS", "EKCH", "EKRK"],
            "source": "obs",
            "hours": [
                {
                    "datetime": "00:00:00",
                    "datetimeEpoch": 1681164000,
                    "temp": 7.9,
                    "feelslike": 3.6,
                    "humidity": 76.09,
                    "dew": 3.9,
                    "precip": 0.0,
                    "precipprob": 0.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": None,
                    "windgust": 42.8,
                    "windspeed": 32.9,
                    "winddir": 130.0,
                    "pressure": 1012.0,
                    "visibility": 10.0,
                    "cloudcover": 88.0,
                    "solarradiation": None,
                    "solarenergy": None,
                    "uvindex": None,
                    "conditions": "Partially cloudy",
                    "icon": "partly-cloudy-night",
                    "stations": ["ESMS", "EKCH", "EKRK"],
                    "source": "obs",
                },
                {
                    "datetime": "01:00:00",
                    "datetimeEpoch": 1681167600,
                    "temp": 7.9,
                    "feelslike": 3.7,
                    "humidity": 81.48,
                    "dew": 4.9,
                    "precip": 0.0,
                    "precipprob": 0.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": None,
                    "windgust": 42.5,
                    "windspeed": 31.1,
                    "winddir": 129.0,
                    "pressure": 1010.0,
                    "visibility": 10.0,
                    "cloudcover": 52.7,
                    "solarradiation": None,
                    "solarenergy": None,
                    "uvindex": None,
                    "conditions": "Partially cloudy",
                    "icon": "partly-cloudy-night",
                    "stations": ["ESMS", "EKCH", "EKRK"],
                    "source": "obs",
                },
                {
                    "datetime": "02:00:00",
                    "datetimeEpoch": 1681171200,
                    "temp": 8.9,
                    "feelslike": 4.9,
                    "humidity": 76.15,
                    "dew": 4.9,
                    "precip": 0.0,
                    "precipprob": 0.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": None,
                    "windgust": 46.1,
                    "windspeed": 33.2,
                    "winddir": 130.0,
                    "pressure": 1008.9,
                    "visibility": 10.0,
                    "cloudcover": 100.0,
                    "solarradiation": None,
                    "solarenergy": None,
                    "uvindex": None,
                    "conditions": "Overcast",
                    "icon": "cloudy",
                    "stations": ["ESMS", "EKCH", "EKRK"],
                    "source": "obs",
                },
                {
                    "datetime": "03:00:00",
                    "datetimeEpoch": 1681174800,
                    "temp": 8.9,
                    "feelslike": 5.0,
                    "humidity": 76.26,
                    "dew": 4.9,
                    "precip": 0.0,
                    "precipprob": 0.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": None,
                    "windgust": 49.3,
                    "windspeed": 31.2,
                    "winddir": 140.0,
                    "pressure": 1007.0,
                    "visibility": 10.0,
                    "cloudcover": 88.9,
                    "solarradiation": None,
                    "solarenergy": None,
                    "uvindex": None,
                    "conditions": "Partially cloudy",
                    "icon": "partly-cloudy-night",
                    "stations": ["ESMS", "EKCH", "EKRK"],
                    "source": "obs",
                },
                {
                    "datetime": "04:00:00",
                    "datetimeEpoch": 1681178400,
                    "temp": 9.0,
                    "feelslike": 5.1,
                    "humidity": 75.53,
                    "dew": 4.9,
                    "precip": 0.0,
                    "precipprob": 0.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": None,
                    "windgust": 49.3,
                    "windspeed": 31.1,
                    "winddir": 141.0,
                    "pressure": 1006.0,
                    "visibility": 10.0,
                    "cloudcover": 88.9,
                    "solarradiation": None,
                    "solarenergy": None,
                    "uvindex": None,
                    "conditions": "Partially cloudy",
                    "icon": "partly-cloudy-night",
                    "stations": ["ESMS", "EKCH", "EKRK"],
                    "source": "obs",
                },
                {
                    "datetime": "05:00:00",
                    "datetimeEpoch": 1681182000,
                    "temp": 8.0,
                    "feelslike": 4.4,
                    "humidity": 80.32,
                    "dew": 4.9,
                    "precip": 0.0,
                    "precipprob": 0.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": None,
                    "windgust": 46.4,
                    "windspeed": 25.5,
                    "winddir": 150.0,
                    "pressure": 1005.0,
                    "visibility": 10.0,
                    "cloudcover": 88.0,
                    "solarradiation": None,
                    "solarenergy": None,
                    "uvindex": None,
                    "conditions": "Partially cloudy",
                    "icon": "partly-cloudy-night",
                    "stations": ["ESMS", "EKCH", "EKRK"],
                    "source": "obs",
                },
                {
                    "datetime": "06:00:00",
                    "datetimeEpoch": 1681185600,
                    "temp": 8.0,
                    "feelslike": 4.2,
                    "humidity": 76.23,
                    "dew": 4.0,
                    "precip": 0.2,
                    "precipprob": 100.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": ["rain"],
                    "windgust": 41.4,
                    "windspeed": 26.7,
                    "winddir": 151.0,
                    "pressure": 1004.9,
                    "visibility": 10.0,
                    "cloudcover": 100.0,
                    "solarradiation": None,
                    "solarenergy": None,
                    "uvindex": None,
                    "conditions": "Rain, Overcast",
                    "icon": "rain",
                    "stations": ["ESMS", "EKCH", "EKRK"],
                    "source": "obs",
                },
                {
                    "datetime": "07:00:00",
                    "datetimeEpoch": 1681189200,
                    "temp": 7.0,
                    "feelslike": 3.8,
                    "humidity": 86.83,
                    "dew": 5.0,
                    "precip": 0.5,
                    "precipprob": 100.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": ["rain"],
                    "windgust": 44.6,
                    "windspeed": 19.0,
                    "winddir": 164.0,
                    "pressure": 1004.0,
                    "visibility": 9.9,
                    "cloudcover": 100.0,
                    "solarradiation": 5.0,
                    "solarenergy": 0.0,
                    "uvindex": 0.0,
                    "conditions": "Rain, Overcast",
                    "icon": "rain",
                    "stations": ["E7634", "ESMS", "EKCH", "EKRK"],
                    "source": "obs",
                },
                {
                    "datetime": "08:00:00",
                    "datetimeEpoch": 1681192800,
                    "temp": 7.0,
                    "feelslike": 3.4,
                    "humidity": 87.25,
                    "dew": 5.0,
                    "precip": 1.0,
                    "precipprob": 100.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": ["rain"],
                    "windgust": 29.2,
                    "windspeed": 21.7,
                    "winddir": 160.0,
                    "pressure": 1004.0,
                    "visibility": 8.9,
                    "cloudcover": 98.3,
                    "solarradiation": 9.0,
                    "solarenergy": 0.0,
                    "uvindex": 0.0,
                    "conditions": "Rain, Overcast",
                    "icon": "rain",
                    "stations": ["E7634", "ESMS", "EKCH", "EKRK"],
                    "source": "obs",
                },
                {
                    "datetime": "09:00:00",
                    "datetimeEpoch": 1681196400,
                    "temp": 7.0,
                    "feelslike": 3.6,
                    "humidity": 93.21,
                    "dew": 6.0,
                    "precip": 0.0,
                    "precipprob": 0.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": None,
                    "windgust": 30.2,
                    "windspeed": 19.9,
                    "winddir": 180.0,
                    "pressure": 1003.9,
                    "visibility": 6.9,
                    "cloudcover": 89.1,
                    "solarradiation": 88.0,
                    "solarenergy": 0.3,
                    "uvindex": 1.0,
                    "conditions": "Partially cloudy",
                    "icon": "partly-cloudy-day",
                    "stations": ["E7634", "ESMS", "EKCH", "EKRK"],
                    "source": "obs",
                },
                {
                    "datetime": "10:00:00",
                    "datetimeEpoch": 1681200000,
                    "temp": 7.0,
                    "feelslike": 4.1,
                    "humidity": 99.37,
                    "dew": 6.9,
                    "precip": 1.1,
                    "precipprob": 100.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": ["rain"],
                    "windgust": 28.4,
                    "windspeed": 16.1,
                    "winddir": 181.0,
                    "pressure": 1003.9,
                    "visibility": 6.2,
                    "cloudcover": 88.8,
                    "solarradiation": 98.0,
                    "solarenergy": 0.4,
                    "uvindex": 1.0,
                    "conditions": "Rain, Partially cloudy",
                    "icon": "rain",
                    "stations": ["E7634", "ESMS", "EKCH", "EKRK"],
                    "source": "obs",
                },
                {
                    "datetime": "11:00:00",
                    "datetimeEpoch": 1681203600,
                    "temp": 7.0,
                    "feelslike": 4.6,
                    "humidity": 99.85,
                    "dew": 7.0,
                    "precip": 0.6,
                    "precipprob": 100.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": ["rain"],
                    "windgust": 31.3,
                    "windspeed": 12.7,
                    "winddir": 161.0,
                    "pressure": 1003.9,
                    "visibility": 6.0,
                    "cloudcover": 89.1,
                    "solarradiation": 81.0,
                    "solarenergy": 0.3,
                    "uvindex": 1.0,
                    "conditions": "Rain, Partially cloudy",
                    "icon": "rain",
                    "stations": ["E7634", "ESMS", "EKCH", "EKRK"],
                    "source": "obs",
                },
                {
                    "datetime": "12:00:00",
                    "datetimeEpoch": 1681207200,
                    "temp": 7.9,
                    "feelslike": 6.0,
                    "humidity": 93.09,
                    "dew": 6.9,
                    "precip": 0.5,
                    "precipprob": 100.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": ["rain"],
                    "windgust": 30.6,
                    "windspeed": 10.8,
                    "winddir": 208.0,
                    "pressure": 1004.0,
                    "visibility": 6.0,
                    "cloudcover": 89.1,
                    "solarradiation": 119.0,
                    "solarenergy": 0.4,
                    "uvindex": 1.0,
                    "conditions": "Rain, Partially cloudy",
                    "icon": "rain",
                    "stations": ["E7634", "ESMS", "EKCH", "EKRK"],
                    "source": "obs",
                },
                {
                    "datetime": "13:00:00",
                    "datetimeEpoch": 1681210800,
                    "temp": 7.9,
                    "feelslike": 7.9,
                    "humidity": 93.4,
                    "dew": 6.9,
                    "precip": 0.2,
                    "precipprob": 100.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": ["rain"],
                    "windgust": 22.7,
                    "windspeed": 4.3,
                    "winddir": 174.0,
                    "pressure": 1004.0,
                    "visibility": 9.7,
                    "cloudcover": 89.1,
                    "solarradiation": 114.0,
                    "solarenergy": 0.4,
                    "uvindex": 1.0,
                    "conditions": "Rain, Partially cloudy",
                    "icon": "rain",
                    "stations": ["E7634", "ESMS", "EKCH", "EKRK"],
                    "source": "obs",
                },
                {
                    "datetime": "14:00:00",
                    "datetimeEpoch": 1681214400,
                    "temp": 8.0,
                    "feelslike": 5.3,
                    "humidity": 92.51,
                    "dew": 6.9,
                    "precip": 0.8,
                    "precipprob": 100.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": ["rain"],
                    "windgust": 18.7,
                    "windspeed": 16.6,
                    "winddir": 241.0,
                    "pressure": 1005.0,
                    "visibility": 10.0,
                    "cloudcover": 89.1,
                    "solarradiation": 280.0,
                    "solarenergy": 1.0,
                    "uvindex": 3.0,
                    "conditions": "Rain, Partially cloudy",
                    "icon": "rain",
                    "stations": ["E7634", "ESMS", "EKCH", "EKRK"],
                    "source": "obs",
                },
                {
                    "datetime": "15:00:00",
                    "datetimeEpoch": 1681218000,
                    "temp": 8.9,
                    "feelslike": 6.5,
                    "humidity": 87.0,
                    "dew": 6.9,
                    "precip": 0.0,
                    "precipprob": 0.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": None,
                    "windgust": 21.2,
                    "windspeed": 16.1,
                    "winddir": 268.0,
                    "pressure": 1005.0,
                    "visibility": 10.0,
                    "cloudcover": 88.3,
                    "solarradiation": 265.0,
                    "solarenergy": 1.0,
                    "uvindex": 3.0,
                    "conditions": "Partially cloudy",
                    "icon": "partly-cloudy-day",
                    "stations": ["E7634", "ESMS", "EKCH", "EKRK"],
                    "source": "obs",
                },
                {
                    "datetime": "16:00:00",
                    "datetimeEpoch": 1681221600,
                    "temp": 8.1,
                    "feelslike": 6.7,
                    "humidity": 86.23,
                    "dew": 6.0,
                    "precip": 0.7,
                    "precipprob": 100.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": ["rain"],
                    "windgust": 18.7,
                    "windspeed": 8.4,
                    "winddir": 278.0,
                    "pressure": 1006.0,
                    "visibility": 10.0,
                    "cloudcover": 99.2,
                    "solarradiation": 492.0,
                    "solarenergy": 1.8,
                    "uvindex": 5.0,
                    "conditions": "Rain, Overcast",
                    "icon": "rain",
                    "stations": ["E7634", "ESMS", "EKCH", "EKRK"],
                    "source": "obs",
                },
                {
                    "datetime": "17:00:00",
                    "datetimeEpoch": 1681225200,
                    "temp": 9.9,
                    "feelslike": 9.9,
                    "humidity": 75.56,
                    "dew": 5.8,
                    "precip": 0.5,
                    "precipprob": 100.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": ["rain"],
                    "windgust": 17.6,
                    "windspeed": 3.4,
                    "winddir": 275.0,
                    "pressure": 1006.9,
                    "visibility": 10.0,
                    "cloudcover": 31.1,
                    "solarradiation": 401.0,
                    "solarenergy": 1.4,
                    "uvindex": 4.0,
                    "conditions": "Rain, Partially cloudy",
                    "icon": "rain",
                    "stations": ["E7634", "ESMS", "EKCH", "EKRK"],
                    "source": "obs",
                },
                {
                    "datetime": "18:00:00",
                    "datetimeEpoch": 1681228800,
                    "temp": 9.7,
                    "feelslike": 7.3,
                    "humidity": 76.14,
                    "dew": 5.7,
                    "precip": 0.3,
                    "precipprob": 100.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": ["rain"],
                    "windgust": 20.2,
                    "windspeed": 17.1,
                    "winddir": 242.0,
                    "pressure": 1007.0,
                    "visibility": 10.0,
                    "cloudcover": 25.0,
                    "solarradiation": 232.0,
                    "solarenergy": 0.8,
                    "uvindex": 2.0,
                    "conditions": "Rain, Partially cloudy",
                    "icon": "rain",
                    "stations": ["E7634", "ESMS", "EKRK"],
                    "source": "obs",
                },
                {
                    "datetime": "19:00:00",
                    "datetimeEpoch": 1681232400,
                    "temp": 8.1,
                    "feelslike": 6.1,
                    "humidity": 80.57,
                    "dew": 5.0,
                    "precip": 0.0,
                    "precipprob": 0.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": None,
                    "windgust": 19.1,
                    "windspeed": 11.2,
                    "winddir": 177.0,
                    "pressure": 1007.0,
                    "visibility": 10.0,
                    "cloudcover": 88.0,
                    "solarradiation": 71.0,
                    "solarenergy": 0.3,
                    "uvindex": 1.0,
                    "conditions": "Partially cloudy",
                    "icon": "partly-cloudy-day",
                    "stations": ["E7634", "ESMS", "EKCH", "EKRK"],
                    "source": "obs",
                },
                {
                    "datetime": "20:00:00",
                    "datetimeEpoch": 1681236000,
                    "temp": 8.0,
                    "feelslike": 8.0,
                    "humidity": 80.83,
                    "dew": 4.9,
                    "precip": 0.0,
                    "precipprob": 0.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": None,
                    "windgust": 13.0,
                    "windspeed": 2.5,
                    "winddir": 149.0,
                    "pressure": 1008.0,
                    "visibility": 8.2,
                    "cloudcover": 87.1,
                    "solarradiation": 28.0,
                    "solarenergy": 0.1,
                    "uvindex": 0.0,
                    "conditions": "Partially cloudy",
                    "icon": "partly-cloudy-day",
                    "stations": ["E7634", "ESMS", "EKCH", "EKRK"],
                    "source": "obs",
                },
                {
                    "datetime": "21:00:00",
                    "datetimeEpoch": 1681239600,
                    "temp": 6.8,
                    "feelslike": 4.9,
                    "humidity": 87.5,
                    "dew": 4.9,
                    "precip": 0.0,
                    "precipprob": 0.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": None,
                    "windgust": 13.3,
                    "windspeed": 9.3,
                    "winddir": 193.0,
                    "pressure": 1008.9,
                    "visibility": 10.0,
                    "cloudcover": 47.7,
                    "solarradiation": None,
                    "solarenergy": None,
                    "uvindex": None,
                    "conditions": "Partially cloudy",
                    "icon": "partly-cloudy-night",
                    "stations": ["ESMS", "EKCH", "EKRK"],
                    "source": "obs",
                },
                {
                    "datetime": "22:00:00",
                    "datetimeEpoch": 1681243200,
                    "temp": 5.9,
                    "feelslike": 3.9,
                    "humidity": 92.69,
                    "dew": 4.8,
                    "precip": 0.0,
                    "precipprob": 0.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": None,
                    "windgust": 12.6,
                    "windspeed": 9.4,
                    "winddir": 248.0,
                    "pressure": 1009.0,
                    "visibility": 10.0,
                    "cloudcover": 29.4,
                    "solarradiation": None,
                    "solarenergy": None,
                    "uvindex": None,
                    "conditions": "Partially cloudy",
                    "icon": "partly-cloudy-night",
                    "stations": ["ESMS", "EKCH", "EKRK"],
                    "source": "obs",
                },
                {
                    "datetime": "23:00:00",
                    "datetimeEpoch": 1681246800,
                    "temp": 5.0,
                    "feelslike": 2.5,
                    "humidity": 98.72,
                    "dew": 4.8,
                    "precip": 0.0,
                    "precipprob": 0.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": None,
                    "windgust": 11.9,
                    "windspeed": 10.6,
                    "winddir": 249.0,
                    "pressure": 1009.0,
                    "visibility": 10.0,
                    "cloudcover": 88.0,
                    "solarradiation": None,
                    "solarenergy": None,
                    "uvindex": None,
                    "conditions": "Partially cloudy",
                    "icon": "partly-cloudy-night",
                    "stations": ["ESMS", "EKCH", "EKRK"],
                    "source": "obs",
                },
            ],
        },
    ],
    "stations": {
        "E7634": {
            "distance": 35013.0,
            "latitude": 55.794,
            "longitude": 12.05,
            "useCount": 0,
            "id": "E7634",
            "name": "EW7634 Skibby DK",
            "quality": 0,
            "contribution": 0.0,
        },
        "EKCH": {
            "distance": 8200.0,
            "latitude": 55.63,
            "longitude": 12.67,
            "useCount": 0,
            "id": "EKCH",
            "name": "EKCH",
            "quality": 49,
            "contribution": 0.0,
        },
        "ESMS": {
            "distance": 52352.0,
            "latitude": 55.55,
            "longitude": 13.37,
            "useCount": 0,
            "id": "ESMS",
            "name": "ESMS",
            "quality": 50,
            "contribution": 0.0,
        },
        "EKRK": {
            "distance": 29493.0,
            "latitude": 55.58,
            "longitude": 12.13,
            "useCount": 0,
            "id": "EKRK",
            "name": "EKRK",
            "quality": 50,
            "contribution": 0.0,
        },
    },
}


def parse_reqest(json_response):
    city = json_response.get("address")

    locations_weather = []
    days = json_response.get("days")
    for day in days:
        row_location_weather = [city]
        print(day.get("temp", 0))
        row_location_weather.append(day.get("temp", 0))
        print(day.get("ndspeed", 0))
        row_location_weather.append(day.get("temp", 0))
        locations_weather.append(row_location_weather)

    df_locations_weather = pd.DataFrame(
        locations_weather, columns=["city", "temp", "wind"]
    )

    df_result = pd.DataFrame([city], columns=["city"])
    df_result["temp_avg"] = df_locations_weather["temp"].mean(axis=0)
    df_result["temp_median"] = df_locations_weather["temp"].median(axis=0)
    df_result["wind_avg"] = df_locations_weather["temp"].mean(axis=0)
    df_result["wind_median"] = df_locations_weather["temp"].median(axis=0)

    return df_result


def process_locations():
    df_locations = pd.DataFrame()
    for location in locations:
        try:
            # url = f"https://weather.visualcrossing.com/VisualCrossingWebServices/rest/services/timeline/{location}/last{scope}days?unitGroup=metric&key={key}"
            # response = requests.get(url)
            response = Response()
            if response.status_code == 200:

                df_location = parse_reqest(response.json())
                # if df_locations.empty:
                #     df_locations = df_location
                # else:
                df_locations = df_locations.append(df_location)
        except Exception as ex:
            print(response.text)

    return df_locations


class Response:
    status_code = 200

    def json(self):
        return json_request


if __name__ == "__main__":
    process_locations()
